name: clashroyalestats
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: 0.6.9
  dio: 3.0.10
  retrofit: 1.3.4+1
  flutter_bloc: 6.1.1
  flutter_hooks: 0.15.0
  freezed_annotation: 0.12.0
  injectable: 1.0.7
  get_it: 5.0.4
  shared_preferences: 0.5.12+4
  flutter_svg: 0.19.1
  hive: 1.4.4+1
  hive_flutter: 0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: 0.6.10
  build_runner: 1.10.13
  retrofit_generator: 1.4.1+1
  json_serializable: 3.5.1
  freezed: 0.12.7
  injectable_generator: 1.0.7
  hive_generator: 0.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/